Wrap output of 'filter' function to a list
With python3 these tests fails with below Error:-

TypeError: 'filter' object is not subscriptable.

'filter' in python3 returns an iterable 'filter'
object, to use it with index need to convert it to list.

Closes-Bug: #1809965
Change-Id: I4ca02849a1c0ca2ea00bc0b86c1c7c452070a770